### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by explodecomputer** [Huuums/vscode-folder-templates#110]
Hi there I just wondered if you could help me out I'm not sure what I'm doing wrong

I'm trying to create a folder that will be named FTName in paramcase, and then for the index.qmd file inside that folder to be opened. What I've done is here - any suggestions what I might be doing wrong? Currently the folder name doesn't get converted and the file doesn't open automatically

https://github.com/explodecomputer/lab-book/tree/main/.fttemplates

**Comment by Huuums** [comment]
You're missing a directory level in your .fttemplates folder. 

It is .fttemplates -> templatename -> <template structure>

So in your example it would be:

```
.fttemplates/
├── standardtemplate/
│   ├── [FTName | kebabcase]/
│   │    ├── index.qmd
│   ├── .ftsettings.json
```

**Comment by explodecomputer** [comment]
It works! Thanks so much, really helpful =]
(openFilesWhenDone works now also!)
