### ISSUE TITLE
Publish Folder Templates to Open VSX

### ISSUE THREAD

**Issue by jthomasmock** [Huuums/vscode-folder-templates#120]
Howdy!

Would it be possible to also publish this extension to the [Open VSX marketplace](https://open-vsx.org/)?

## Context
Microsoft prohibits use of the Microsoft VS Code marketplace by any other products or redistribution of .vsix files from it. Great extensions like Folder Templates are thus not easily accessible in many other environments even though the the extensions are open source and compatible. 

## What is Open VSX? Why does it exist?

> As an open alternative to the Visual Studio Marketplace, the Open VSX Registry offers free access to extensions that can be used with any technology or tool that supports them. - [Eclipse Foundation](https://www.globenewswire.com/news-release/2023/06/27/2695137/0/en/The-Open-VSX-Registry-a-Vendor-Neutral-Community-Supported-Alternative-to-the-Visual-Studio-Marketplace-Gets-its-Own-Working-Group-at-the-Eclipse-Foundation.html)

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io/), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [coder](https://github.com/coder/code-server), [Cursor](https://www.cursor.so/), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?
The docs to publish an extension can be found at [Publishing-Extensions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). There's also [GitHub Action for publishing](https://github.com/HaaLeo/publish-vscode-extension#readme) explaining the whole process with an example GitHub Action workflow.

**Comment by Huuums** [comment]
Hey, sure i'll try to figure that out in the coming days. Thanks for the hint. I didn't even know the open vsx marketplace was a thing.

**Comment by jthomasmock** [comment]
Thanks for considering!

**Comment by Huuums** [comment]
Published the extension to open-vsx. https://open-vsx.org/extension/Huuums/vscode-fast-folder-structure
