### ISSUE TITLE
Variable %USERPROFILE% in settings

### ISSUE THREAD

**Issue by Voha888** [Huuums/vscode-folder-templates#121]
For the convenience of working on several computers, in the Vscode settings for **Windows 10 x64** I specified the following path to the templates folder in the extension settings:
`%USERPROFILE%\OneDrive\Project\Folder_template\`

But it seems the extension doesn't understand the **%USERPROFILE%** variable?

**Comment by Huuums** [comment]
Hey, 

yes it is true that the extension does not know about the %USERPROFILE% variable. I'm sure it can be added. I will take a look at that when I find the time. If you have any time yourself you would also welcome to create a PR

**Comment by Huuums** [comment]
hey @Voha888 

just published an update to include this. Instead of %USERPROFILE% please use %HOME%
