### ISSUE TITLE
adding a template at the focus location (idea)

### ISSUE THREAD

**Issue by MrOxMasTer** [Huuums/vscode-folder-templates#124]
I want to get rid of the influence of a computer mouse as much as possible, and therefore I would like to create templates using a keyboard shortcut. 

Templates can either be created by PCM by folder and "create New Template folder", or you can configure a keyboard shortcut.

But the keyboard shortcut can be directed to one action such as "FT.createFolderStructure" and the problem is that when my focus goes to explorer and I try to create a template, it does not determine where I am and I have to write the path every time to the point where I need to create a template when using keyboard shortcuts. 

I think it would be a cool idea if extensions would determine where the focus is and create where I have focus now, like the keyboard shortcuts built into vs code: "ctrl + N" - create a new file, "ctrl + shift + N" - create a new folder

**Comment by Huuums** [comment]
Hey, thanks for reaching out. This is something I wanted to add for a while but I didn't find any API to implement this. 
However as I just googled around a bit more i finally found something that might get it to work. 

I will try to implement this when I find the time. 

Reminder for myself: https://github.com/Microsoft/vscode/issues/3553#issuecomment-1098562676

**Comment by MrOxMasTer** [comment]
> Hey, thanks for reaching out. This is something I wanted to add for a while but I didn't find any API to implement this. However as I just googled around a bit more i finally found something that might get it to work.
> 
> I will try to implement this when I find the time.
> 
> Reminder for myself: [microsoft/vscode#3553 (comment)](https://github.com/microsoft/vscode/issues/3553#issuecomment-1098562676)

Wow, great, thanks a lot!

**Comment by MrOxMasTer** [comment]
> > Hey, thanks for reaching out. This is something I wanted to add for a while but I didn't find any API to implement this. However as I just googled around a bit more i finally found something that might get it to work.
> > I will try to implement this when I find the time.
> > Reminder for myself: [microsoft/vscode#3553 (comment)](https://github.com/microsoft/vscode/issues/3553#issuecomment-1098562676)
> 
> Wow, great, thanks a lot! Happy New Year)
