### ISSUE TITLE
change place where directory with templates should be placed 

### ISSUE THREAD

**Issue by Cabagemage** [Huuums/vscode-folder-templates#126]
As I see, to use templates, I should place it in root directory of project (or inside directory with plugin). But what can I do, if I want to place it inside another dir ? 

```
root 
--.vscode
--src
  -.ftttemplates
```

Is it able to do ? 

Also, thank you for plugin, its good solution to solve routine :)

**Comment by nickiepucel** [comment]
@Cabagemage have you tried using the [`templateFolderPath`](https://github.com/Huuums/vscode-folder-templates?tab=readme-ov-file#foldertemplatestemplatefolderpath) setting?

I think that this is what you're looking for.

**Comment by Huuums** [comment]
Please see nickiepucels answer above. That should do what you need. If not feel free to come back :)
