### ISSUE TITLE
Create a list of common Temlate formats and let them be added via command

### ISSUE THREAD

**Issue by Huuums** [Huuums/vscode-folder-templates#35]
Due to the removal of default templates the "out of the box" usability of the plugin kind of disappeared. 

Creating a list of common Folder structures and have them be addable via some command should make the plugin more userfriendly for people who do not have a special usecase.

**Comment by Huuums** [comment]
I would love if some people post their structures here so that we can have a nice list of common patterns.

**Comment by njoppi2** [comment]
"fastFolderStructure.fileTemplates": {
    "index": [
      "import React from 'react';",
      "import { Container } from './styles';",
      "",
      "interface Props {",
      "}",
      "",
      "const <FFSName>: React.FC<Props> = () => {",
      "  return (",
      "    <Container>",
      "      ",
      "    </Container>",
      "  );",
      "}",
      "",
      "export default <FFSName>;"
    ],
    "styles": [
      "import styled from 'styled-components';",
      "import Config from 'config';",
      "",
      "export const Container = styled.div`",
      "\t",
      "`;",
      ""
    ]
  },

    "fastFolderStructure.structures": [
      {
        "name": "Default",
        "structure": [
          {
            "fileName": "index.tsx",
            "template": "index"
          },
          {
            "fileName": "styles.ts",
            "template": "styles"
          }
        ]
      },
    ],

**Comment by Huuums** [comment]
no longer needed
