### ISSUE TITLE
Location of templates

### ISSUE THREAD

**Issue by oxk4r01** [Huuums/vscode-folder-templates#39]
Is actually possible to store templates in a different place than settings.json? I feel this not very convenient...

**Comment by Huuums** [comment]
As of now that's the only place to store templates as I felt that was alot more convenient. But I'm open to suggestions, what would you prefer?

Would you like to save the complete directory at the root of the project? Or in some global vscode folder?

**Comment by oxk4r01** [comment]
Hi, in my opinion, I think that a dedicated folder would be a good choice.
