### ISSUE TITLE
Feature-Request: Default-Values for customVariables

### ISSUE THREAD

**Issue by N7K4** [Huuums/vscode-folder-templates#40]
It would be nice to define default-Values for the customVariables. 

E.g. 

```json
"customVariables": [
   "Company"
]
```

could be

```json
"customVariables": [
   "Company: 'my company ltd.'"
]
```

Adding a default value, to the company variable, would be great, so you can just press ENTER to continue w/o typing the full company name.

**Comment by Huuums** [comment]
Moin Moin, 

thanks for the suggestion. I really like it!

I will probably need some time to get to the change but it will definitely happen.
