### ISSUE TITLE
Feature Request: Omit FTName when using Custom Variables (only)

### ISSUE THREAD

**Issue by N7K4** [Huuums/vscode-folder-templates#43]
I like your add-in / extension very much!

I am using your extension with **custom variables only**. I do not use the "default" variable `FTName` . To avoid just jumping over the 1st step, where the extension is asking for FTName. It would be nicer to have an omit feature in the config section similar to the `omitParentDirectory` toggle.

Is there a technical need for the `FTName` variable?

**Comment by Huuums** [comment]
Moin,

thanks for reaching out. 

There's no real need for the `FTName` other than I never got around to make it optional. 

I will definitely get to this shortly.
