### ISSUE TITLE
Use .fttemplates in project root

### ISSUE THREAD

**Issue by subzero79** [Huuums/vscode-folder-templates#48]
Hi there, thanks for this extension  works very well.

Do we have to specify the folder in workspace settings.json for .fttemplates to work ? 
at the moment it keeps defaulting to the global extensions .fttemplates folder

Thanks

**Comment by Huuums** [comment]
Moin, thanks for reaching out. You don't need to specify the folder in the settings file. Having the folder at the project root is enough. 

The global folder will however still be used in addition to the local .fttemplates folder to read templates. (I should probably make this configurable)

If it doesn't work I would appreciate if you could create a small repo which replicates your issue so I can take a more detailed look :)
