### ISSUE TITLE
I can't create a folder inside a folder

### ISSUE THREAD

**Issue by pdgustavo** [Huuums/vscode-folder-templates#52]
Hi,

I am able to create folders using EmptyDirectory value but I can't create a folder inside a folder

**Comment by Huuums** [comment]
Moin, thanks for reaching out. Do you define your templates in a .fttemplates folder or via the settings file? Could you please show me how you're trying to achieve to create nested folders?

**Comment by Huuums** [comment]
I just tried to reproduce it and it works for me. So feel free to post your structure here and i'll take a look

**Comment by pdgustavo** [comment]
Hey, I tried to use the .fttemplates folder now and ir all worked good! I couldn't accomplish that via settings though.

Really good jod, by the way! Thank you so much!

**Comment by pdgustavo** [comment]
Hey, if I can give you a suggestion, I'd recommend you to add an icon to the extension. People usually go quicker to the extensions that have an icon. Such a powerful tool needs to be used by more people.

Thank you again!

**Comment by Huuums** [comment]
Thanks for the suggestion.  The Latest update added an icon
