### ISSUE TITLE
Are multiple interpolations possible?

### ISSUE THREAD

**Issue by osequi** [Huuums/vscode-folder-templates#55]
I'm trying something like `<FTName | capitalize | singular>` but it's left uncompiled. Is chaining possible?

Thanks a lot!

**Comment by Huuums** [comment]
Hi @osequi, thanks for reaching out.

Please take a look at the documentation.

You can find an example how to chain interpolations in there:
`<FTName | capitalize?singular>`

**Comment by osequi** [comment]
Thanks! 

Ok I see now. The info was hidden in the 4th column / nth row of a table :)
