### ISSUE TITLE
Templates from ".fttemplates" not working on Windows D: Drive.

### ISSUE THREAD

**Issue by yourimiyi** [Huuums/vscode-folder-templates#57]
Hi, thank you for your great work! it is so amazing extension that I tried to find desperately.

I got `"Something went wrong getting Folder contents"` error message when I trying to create new folders from File Explorer tab.

![image](https://user-images.githubusercontent.com/9496172/113495834-29aae800-952f-11eb-868c-cee4643d9dda.png)

Here is stack trace.
`lib/fsHelper.ts: line 25`
![image](https://user-images.githubusercontent.com/9496172/113495868-637bee80-952f-11eb-87a3-223e52985fc5.png)

Templates folder located at D: drive's `D:\00. Template\UI\.fttemplates`.
so, `lib/extensionHelpers.ts: line 49` - `vscode.Uri.parse` do split folder name as "D:" to scheme and others to path
![image](https://user-images.githubusercontent.com/9496172/113495893-932af680-952f-11eb-9f2b-91ca56792e2f.png)

```typescript
export const getTemplatesFromFS = (folderPath: PathLike) => {
  const fsTemplates = readdirSync(folderPath, { withFileTypes: true });
  return fsTemplates
    .map((file) => {
      if (!file.isDirectory()) {
        return null;
      }
      const settings =
        parseSettingsFile(`${folderPath}/${file.name}/.ftsettings.json`) || {};

      const contents = getFolderContents(
        vscode.Uri.parse(`${folderPath}/${file.name}`) // <<<<< HERE!!!
      );
```

I don't know how can fix this issue.

Anyway, THANK YOU again.

**Comment by Huuums** [comment]
Moin,

thank you for finding this. 

This will be fixed in the next version
