### ISSUE TITLE
Documentation Clarity

### ISSUE THREAD

**Issue by soulshined** [Huuums/vscode-folder-templates#61]
The documentation for this is really confusing in my opinion. I've spent about 20 minutes trying to figure out how to add sub-folders in settings and just can't do it. It took me about 10 minutes just to find out how to create an empty directory because the disclaimer about it is not prominently displayed in the readme my opinion, or at least positioned well.  I personally feel 20 minutes to learn how to use an extension is too long when something like `EmptyDirectory` can simply be autocompleted with hints and suggestion details. I'm not saying I'm the smartest guy in the world, but I'm not that slow. The only issue I found on this repo asking about the same thing didn't provide a programmatic solution, It appears they ultimately went with creating it in the global `.fttemplates` directory, which is great.

I personally don't want to do that because I use multiple vscode instances and prefer to have my settings synced so I can just log on and go. 

I don't want to tell you how to do your extension but can I recommend some things that I feel would provide a better user experience?

- Include example values for setting configurations [here](https://github.com/Huuums/vscode-folder-templates/blob/72f284fc584074798f9fdbe2b0dc9f3b087f8f19/package.json#L59-L69)
- Include a proper json schema for setting configurations [here](https://github.com/Huuums/vscode-folder-templates/blob/72f284fc584074798f9fdbe2b0dc9f3b087f8f19/package.json#L59-L69)
- Include a json schema validator for `.ftsettings.json` files [reference](https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation) 
  This allows the same autocomplete and suggestion details to be populated for any `.ftsettings.json` files. (You would also need to set your package.json `activationEvents` to activate on these files as well so the validator will run automatically)

I think doing those 3 simple things would align your extension with the behavior people expect using vscode and would help new adopters like me tremendously. It would autonomously provide error handling as well and visually identify to the user what they are doing wrong without any input from you as the developer.

If you don't have time to do the above, I would be glad to provide a PR for you - no issues with that, I would just need a complete understanding of the data structures, but interim would you mind providing insight on how to create subfolders in a settings structure? I really like the idea of this extension and don't want to give up on it yet based on others I've found in the marketplace

**Comment by Huuums** [comment]
Thank you for reaching out. 

I 100% agree with you that the documentation is more complicated than it has to be. Unfortunately I'm not good at writing documentation but I will try to make it clearer nonetheless.

Thank you for the pointers. These are very helpful and I will definitely incoroporate them shortly. 

For now I hope this example will answer your question. If not feel free to contact me again :)

```jsonc
"folderTemplates.structures": [
    {
      "name": "Example Template",
      "structure": [
        {
          "fileName": "index.js",
          "template": "indexfile"
        },
        {
          "fileName": "emptysubfolder",
          "template": "EmptyDirectory"
        },
        {
          "fileName": "subfolder/emptynestedsubfolder", 
          "template": "EmptyDirectory"
        },
        {
          "fileName": "subfolderwithfiles/subfolderfile.txt", //to create subfolders just put the whole path to the file, the folders will be created recursively if they do not exist yet
          "template": "subfolderfile"
        },
        {
          "fileName": "subfolderwithfiles/nestedsubfolder/nestedsubfolderfile.txt",
          "template": "nestedsubfolderfile"
        }
      ]
    },
    {"name": "structure2", "structure":[]}
],
"folderTemplates.fileTemplates": {
    "indexfile": "just an index file",
    "subfolderfile": "content for subfolderfile",
    "nestedsubfolderfile": ["content for nested subfolderfile", "", "", "with multiple lines"]
}
```

**Comment by soulshined** [comment]
Oh beautiful! Okay that makes sense! That easily clears it up and I don't have any follow-ups. Thanks so much for the swift response @Huuums 

If you want a PR or don't have time just let me know - my offer still stands. Thanks again for the swift response, I appreciate it and this extension! Very useful

**Comment by soulshined** [comment]
I didnt mean to close it, that was a misclick, I'll leave it up to you if you want to keep it closed or not. Sorry.

Just to provide some context on why I was confused so maybe it could help shape your approach:

I was trying to create 'sub structures' for subfolders:

```
"folderTemplates.structures": [
    {
      "name": "Example Template",
      "structure": [
        {
          "name": "subfolder1",
          "structure: [
                  {
                     "fileName": "subfolder1_file_1.txt"
                  }
           ]
       },
```

I can see now that was really wrong :) but that was how it read to me or how I assumed it would need to be done because I didn't catch any examples in the readme with subfolders (but now I also see there is one small one in there). I also think that 'fileName' was misleading me when I was looking for ways to add 'folderName', but how you have it makes sense now that I understand how to do it!

So hopefully that provides more context on what adopters may be thinking. Hopefully everyone isn't thinking like me though!
