### ISSUE TITLE
Feature Request - Explicitly overwrite existing files

### ISSUE THREAD

**Issue by soulshined** [Huuums/vscode-folder-templates#63]
Greetings,

I have been enjoying the extension very much. Thank you. After about a week of using it I think it satisfies almost all my development needs. I just have a feature request around overwriting existing files.

Currently, the control flow identifies if a file already exists and omits from creating it (again). It then notifies the user of said file not being generated. This is all great and I'm sure has saved a ton of trouble by accidentally overwriting something. But may I propose some alternates to give some flexibility to end-users here?

- Add an option to allow only overwriting if the file is tracked (the workspace has an active git init and the file is not ignored)
- Add an option to allow overwrite in specific globs (i.e., `**/tests/**`) [I would recommend something like [node-glob](https://github.com/isaacs/node-glob)]
- Add an option to allow overwrite for a specific filename or extension
- Add an option to allow overwrite based on language specific configurations [reference](https://code.visualstudio.com/docs/getstarted/settings#_languagespecific-editor-settings)
- Or possibly consider 'merging files' - this would be complicated, but if you keep the scope of what can be merged it may relieve a lot of technical debt.

It might be beneficial to consider adding this functionality to ftsettings.json files so it's project scoped, but I think, or I'm assuming, these would really be one-time configurations yeah? I think people would just add it to user-settings, but that's just food for thought. 

I wouldn't recommend an option to always overwrite, but that's your call obviously. I think the key here is just flexibility being sufficient. And I think the proposed options are future proof that wouldn't require much maintenance in the future, but I would love to see what others contribute in that regard. 

My use-case is that I have an extension that automatically generates a project-based `.vscode/settings.json` file every folder that is opened, for other reasons beyond the scope of this extension (like setting up envs). 

Using this extension in tandem sort of complicates that pattern. For example, if you were to create a folder structure specifically targeting typescript and you include a `.vscode/settings.json` file in that template with language-specific settings or a setting to exclude javascript files from search and the explorer, it wouldn't be applied with the template if it already exists. These aren't settings I need in every project, obviously if I'm doing something in python,  just for example. 

This would work great, but since I have another extension that automatically creates a settings file at launch for other reasons, this extension identifies it as existing and omits it. And as far as I know, you can't alter the order of loading extensions. 

FYI, I understand having more settings than you need doesn't hurt you, I just share a lot of my settings with projects with other people or when I upload something to github, so they have what I have. Easier for troubleshooting etc, so keeping them relative just makes it easier to find, clutter-free and respective.

Any thoughts on this?

**Comment by Huuums** [comment]
Moin, 

I think making the overwriting of files customizable is a very good idea. 

But I'm thinking more along the lines of a simple new property in the settings of a structure.

```
"overwriteExistingFiles":  "never" | "always" | "prompt"
```

where `never` (default) would not overwrite existing files. `always` would overwrite them. 

If the value is `prompt` the extension would show a list of files that would potentially be overwritten. You would then check or uncheck every file in the list to mark it to be overwritten or not.

I think that should satisfy all usecases. There might be structures where you're sure you want to overwrite all files. Sometimes you might want to choose if you want to overwrite any. And with most structures you don't want to overwrite any files. 



I personally think this is overkill but one could take it up a notch and even go with something like this

```json
overwriteExistingFiles: {
".json": "always",
".jsx": "prompt"
}
```
But I'd really not like to go so indepth with this. It's overcomplicating things. At least in my personal opinion.

**Comment by soulshined** [comment]
> But I'm thinking more along the lines of a simple new property in the settings of a structure.
> 
> ```
> "overwriteExistingFiles":  "never" | "always" | "prompt"
> ```
> 
> where `never` (default) would not overwrite existing files. `always` would overwrite them.

That's a great approach I think! 

Although I think node-globs idea can come in handy personally! It's very lightweight and that package is super simple to incorporate. Maybe consider it, but overall I think what you have mentioned will help a ton! I didn't know you could prompt for a user-defined list of choices. I just learned something, though to be fair I don't read through the API too often! I am just a fan of not using my mouse unless I absolutely need to, but I understand the world can't revolve around me!

I think in your approach, it would make sense to add it to ftsettings files too, since users may want a template structure that automatically overwrites in one scenario but not another.

Thanks for the discussion on this! Sounds great

**Comment by soulshined** [comment]
Thanks @Huuums can't wait to use this bad boy! This may be my fault for not reviewing, but the schema validation files can't be found. I didn't think to check your `vscodeginore` file but it appears it's being ignored from the deployment package: [https://github.com/Huuums/vscode-folder-templates/blob/43a2d44fdbd64a2d441e801eada80aa8ddd1573d/.vscodeignore#L4](https://github.com/Huuums/vscode-folder-templates/blob/43a2d44fdbd64a2d441e801eada80aa8ddd1573d/.vscodeignore#L4)
since they reside in `src/schemas`

easy fix though! just filling you in. Thanks for the quick turn around on this. I appreciate it

**Comment by Huuums** [comment]
Thanks for the pointer. Fixed it just now
