### ISSUE TITLE
Configurable template directory

### ISSUE THREAD

**Issue by deasems** [Huuums/vscode-folder-templates#66]
Thanks for the extension, it works well and saves a lot of time 👍 

I'd like to be able to configure the directory where the extension looks for templates. This would help me keep my root directory organized.

**Comment by Huuums** [comment]
Hey @deasems. Sorry, I somehow missed this issue. 

Thank you for the suggestion. Makes alot of sense. I will implement this soonish.

**Comment by Huuums** [comment]
Hey @deasems , thanks again for the idea.

I just published a new version. Feel free to take a look at this new configuration option: https://github.com/Huuums/vscode-folder-templates#foldertemplatestemplatefolderpath
