### ISSUE TITLE
Replace space with underscore

### ISSUE THREAD

**Issue by magick93** [Huuums/vscode-folder-templates#67]
Hello

Thanks for this extension. It is a huge time saver!

Is it possible to replace spaces with underscores? Or perhaps something more flexible such as a general `replace(" ", "_")` function?

Thanks

**Comment by Huuums** [comment]
Hey, thanks for reaching out. 

I don't think there is a way to achieve this right now. The closest thing would be the snakecase transformer. However that one also lowercases the first letter behind the underscore. 

However having something like a replace function (very rudimentary static replacements only) might be useful and I think I should have time to implement it soonish

**Comment by Huuums** [comment]
Moin @magick93 ,

I just published a new version of the extension. It includes a new replace transformer which should do what you need.

You can find it here: https://github.com/Huuums/vscode-folder-templates#interpolation

It's essentiall used like this. 

<FTName | replace(' ', '_')> which would change  "This new Component" to "This_new_Component". 

Please note that you can only use single quotes inside the replace transformer. double quotes will not work to annotate the strings
