### ISSUE TITLE
Error when adding .ftsettings.json

### ISSUE THREAD

**Issue by JosephDAM** [Huuums/vscode-folder-templates#71]
Hi, when I create a template in the file system I get an error if I add a .ftsettings.json.
My template looks like this:
![image](https://user-images.githubusercontent.com/6605055/129707770-84ba15f0-e4ba-4714-a60d-404ca17efea5.png)

If I leave it like that, the context menu "Create New Templated Folder" does not do anything on click.
If I open de Command Palette and execute  "Create New Templated Folder", it does not ask for a template, it directly goes to the name propmt (even tho I have more than one template defined). In this prompt, if I input something and press Enter, or if I just press Escape, I always get this error:
![image](https://user-images.githubusercontent.com/6605055/129708088-549ca594-e183-4425-a2b0-65767514110d.png)

If I define the same template in the settings.json, it works just fine.
If I remove the .ftsettings.json. it also works.

Thanks

**Comment by Huuums** [comment]
Hey @JosephDAM, thanks for reaching out. 

Could you please show the contents of the .ftsettings.json file?

I've tried to reproduce it but couldn't unfortunately.  

It would also help if you could show the folder containing your templates. You don't need to expand them all, I just would like to see the overall structure to be able to understand what's happening and if there's maybe something wrong on that end.

**Comment by JosephDAM** [comment]
Sure, here you go:
![image](https://user-images.githubusercontent.com/6605055/129717605-da6ce257-4a8b-4ade-b830-44a08f95f561.png)

I've removed the .ftsettings.json file from the Customvariables example template. Same issue.

Thanks

**Comment by Huuums** [comment]
What I can see from that screenshot is that the `.fttemplates` folder is not on rootlevel of the vscode project. If you use the extensions default settings that won't work. 

You can do either of these two things to fix the problem for this particular project
- put the `.fttemplates` folder at the root of the project.  
- set the `folderTemplates.templateFolderPath` setting to `wwwroot/.fttemplates`. 

Does that fix the issue?

**Comment by JosephDAM** [comment]
If I set folderTemplates.templateFolderPath to wwwroot/.fttemplates it does not find the templates anymore.
If I leave the folderTemplates.templateFolderPath with its default value and remove the .ftsettings.json file from the templates, it finds my custom templates, and creates them properly. The only problem is when one of the templates has a .ftsettings.json, then, it seems to get some kind of error when loading the templates.
My project is in another PC, im accesing the code via the internal network. I'm not sure if that could be an issue.

**Comment by Huuums** [comment]
Thank you very much for the detailed information. 

I'm really sorry but I'll have to ask you to wait a bit for this to be resolved. I'm not sure where the problem is and I don't have the time to check it before the weekend

**Comment by Huuums** [comment]
@JosephDAM 

So I had a little time to look into this and I still have no clue. Would it be possible for you to give me an error log? 

In VSCode open the command palette and select `Show Logs...` and then choose `Extension Host`. 

When it's open you just reproduce the error and hopefully the errorlog should be popping up in there. 

If you could paste that in here it would be greatly appreciated.
