### ISSUE TITLE
How to create folder with specific path by .fttemplates

### ISSUE THREAD

**Issue by nguyen-quang-phu** [Huuums/vscode-folder-templates#72]
Hello, I just used your extension recently. I feel your extension very nice and convenient. I very like it.
I config setup with settings.json and extension working very well.
 But if i config in settings.json, file will long and difficulty read. So i config with .fttemplates.
I read document and i see .fttemplates don't set specific path for folder template.
Example, I set folder src is root folder. When I create 1 component, component in folder src/components:
![Screenshot from 2021-09-04 00-17-11](https://user-images.githubusercontent.com/43996827/132043661-4ad6e149-8ae8-4f31-9aeb-88f0abec7f07.png)
Key binding:
![Screenshot from 2021-09-04 00-20-45](https://user-images.githubusercontent.com/43996827/132043899-6a27e6ee-ac42-48aa-813b-9cb5b3b9177f.png)

With settings.json, I can set specific path for template in fileName.
With .fttemplates. I try set name property .ftsettings.json. It not working. It will folder templace in src folder.
![Screenshot from 2021-09-04 00-23-28](https://user-images.githubusercontent.com/43996827/132044197-0ebc54aa-9b68-479c-b984-201e4ecb845c.png)
Do you have any solution for this problem? I think i set different keybinding with different args but it's quite inconvenient.

**Comment by Huuums** [comment]
Hey, thanks for reaching out. 

There is not a nice way to do this with the extension right now without setting up another keybind. 

However you can do a bit of a hack to achieve this. 

This is what the template would look like. (The "Template Name" Example)
![image](https://user-images.githubusercontent.com/9745322/132050633-4f36e341-1a55-4ce8-b2ed-13d24a8188f2.png)


And in the `.ftsettings.json` file you need set `omitParentDirectory: true`. 
![image](https://user-images.githubusercontent.com/9745322/132050813-f3ba3797-5e1b-4d74-928e-173369ddce1b.png)



So in your specific example just put the `[FTName].css`, `[FTName].ts`, and `index.ts` file in another folder named "components" inside the Template and then set the `omitParentDirectory` option to true in the .ftsettings.json 


If this works for you and is enough as a solution feel free to close the issue :)

**Comment by nguyen-quang-phu** [comment]
It works exactly what i need. Thank you so much. This is a wonderful extension.
