### ISSUE TITLE
set a default entry file for a folder template

### ISSUE THREAD

**Issue by czpcalm** [Huuums/vscode-folder-templates#73]
This is what I just want for these days! And I think it would be better if a file in the folder template can be open to edit. Is it possible?

**Comment by Huuums** [comment]
Hey. 

Do I understand it correctly that you would like to specify if a file should be automatically opened in the editor after creating the template?

**Comment by czpcalm** [comment]
@Huuums Yes (Sorry for my poor English). I think that would be great.

**Comment by Huuums** [comment]
@czpcalm This functionality has just been added thanks to @ThumNet . I will publish the new version in a bit.
