### ISSUE TITLE
combine transformations in file name ("?" operator)

### ISSUE THREAD

**Issue by jrmora** [Huuums/vscode-folder-templates#75]
It will be interesting to have the feature to combine transformations for the file/folder name with any operator.

Inside a file we can use "|" and "?"  Example:  
`<FTName | lowercase?pascalcase>`

but for the file and folder name we must use only one with "%" Example:
`[FTName % pascalcase].tsx`

**Comment by Huuums** [comment]
Thanks for reaching out. 

This was an oversight. I didn't check if the `?` character was forbidden in filenames. 

I went ahead and added the `&` operator to chain transformers. So in filenames you can now chain transformers like this `[FTName % lowercase&pascalcase]`. You can of course also use the `&` operator generally to chain transformers. 

That feels more natural to me too.

**Comment by jrmora** [comment]
Excellent, just try to add it to the Doc.

Thank you, and good job!
