### ISSUE TITLE
Doesn't create folders with only omitParentDirectory and omitFTName set to true

### ISSUE THREAD

**Issue by green-anger** [Huuums/vscode-folder-templates#79]
Hello,

Thank you for the great plugin! It does the job, however not in the following use case.

I use this approach - [Creating templates on the File System](https://github.com/Huuums/vscode-folder-templates#creating-templates-on-the-file-system), .ftsettings.json is very simple:
```
{
  "omitFTName": true,
  "omitParentDirectory": true
}
```
Just to make sure the order doesn't matter I tried this as well:
```
{
  "omitParentDirectory": true,
  "omitFTName": true
}
```
Does nothing. If I change this to
```
{
  "omitFTName": false,
  "omitParentDirectory": true
}
```
or remove `omitFTName": true` then it works but asks for a component name, so I have to enter a dummy value (don't use it).

Adding a custom variable (e.g. as in [this example](https://github.com/Huuums/vscode-folder-templates/tree/master/examples/No%20FTName)) also works but then it asks for the variable value (even if there's a default value, it's just prepopulated), so it's also extra clicks.

In both cases it's not a big deal to do extra clicks comparing to the received value the plugin provides, but I think getting things done in as less actions as possible is in the spirit of the plugin. And it's always possible I've missed something and don't use it right, then please let me know.

Thanks again!

**Comment by Huuums** [comment]
Hey,

I think this is a case I just didn't think of yet. I imagine you're bootstrapping a project rather than creating a component if you don't need any variables.

This is an oversight and I agree that your workarounds shouldnt be necessary for such a simple usecase. It will be fixed in the coming days.

Thanks for the report!

**Comment by green-anger** [comment]
Thanks for the prompt response! You're absolutely right, I need to bootstrap a project with complex folder structure which is tedious to create manually, so the plugin saves a lot of time there.

Looking forward to the update, many thanks!
