### ISSUE TITLE
Absolute paths

### ISSUE THREAD

**Issue by hondzik** [Huuums/vscode-folder-templates#82]
Hi,
I need all files of one type to be created inside specific folder, something like ./AA/BB/[FTName].json
Is it possible to specify absolute path for the new file(s)?

Thanks

**Comment by Huuums** [comment]
I hope I understood your question correctly. Does this look like something you would like to achieve?  

```
...projectroot 
- src
   - JSON
      - <create json file here>
   - components
      - <create main folder here>
```

Right now there's no way to have absolute paths for files and I'm thinking that it might be very hard to implement too. I have to think a bit about it.

However if what you need is what I illustrated above then you can use a workaround to achieve that right now. 

This is what the template inside the .fttemplates folder would look like. 

![image](https://user-images.githubusercontent.com/9745322/146761163-faa0caec-71a5-4283-8980-f22b91d1bf28.png)

the content of the `ftsettings.json` is
```
  {
     "omitParentDirectory": true
  }
``` 

If you then rightclick on the `src` folder (this is important) and then click "Create New Templated Folder" it would create the files like this.

![image](https://user-images.githubusercontent.com/9745322/146761439-e5a1acca-9330-4cb1-9296-fd9fbc1453a6.png)

I prepared this template as a zip. If you want feel free to download this template here
[Template.zip](https://github.com/Huuums/vscode-folder-templates/files/7744951/Template.zip)

**Comment by hondzik** [comment]
Hi,
I will try to specify the use-case on better example.
We use quite deep folder structure. For example we have ...projectroot/src/config/lovs folder, where we store "list of values" definitions in JSON format. I would like to be able to create files from selected template always in this directory, doesn't matter if the user triggers file creation by rightclicking on src, config or lovs folder.

Thank you for your help

**Comment by Huuums** [comment]
Ah I see. 

Yes that's currently not possible. I have a rough idea of how to implement it but it's something that has to be done first. 

I don't think this will happen before new year unfortunately

**Comment by hondzik** [comment]
I tried to implement the change myself. Please see #83

**Comment by Huuums** [comment]
I fixed a small typo and merged. thank you :)

**Comment by hondzik** [comment]
Thanks :)

**Comment by Norfeldt** [comment]
@hondzik @Huuums having a little trouble making it work.

![Mar-03-2022 12-48-37](https://user-images.githubusercontent.com/678806/156559231-fd142112-6114-49bf-a9b7-3cd4b204150e.gif)
