### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by diegodls** [Huuums/vscode-folder-templates#91]
Hey guys, there's a way to add **_vscode's snippets when creating templates_**?

Actual method:

` {
          "fileName": "index.tsx",
          "template": "React Native Functional Component"
        },
`

What i want:

`
 {
          "fileName": "index.tsx",
          "template": rnfc << my snippet"
        },
`

I tried using variable and won't work, any tip or method?

Thanks.

**Comment by Huuums** [comment]
Hey, 

right now there's no way to do this.

I'll take a look at this in the near future.

**Comment by diegodls** [comment]
Ok, no problem.
Thanks.

**Comment by Huuums** [comment]
Sorry for coming back so late to this and also with the bad news that this doesn't appear to be possible. 

I did not find a way to read snippets from the extension interface.
