### ISSUE TITLE
Spaces at the ends of Foldernames

### ISSUE THREAD

**Issue by SpiritSeal** [Huuums/vscode-folder-templates#92]
Attempting to pass spaces at the end of an instance foldername goes through, creating such folder. This causes issues with many things, such as preventing `Code Runner` from running the code and preventing the user from opening said folder or it's children using the `Reveal in File Explorer` Command.
As VSCode itself prevents you from creating folders of this type, this is likely a bug.

![image](https://user-images.githubusercontent.com/45369057/154809768-3395dfac-6a42-4dfb-86b8-775a5adf7d2b.png)
![image](https://user-images.githubusercontent.com/45369057/154809788-4e16a66a-fadf-464a-bb29-2811fdb44a95.png)
![image](https://user-images.githubusercontent.com/45369057/154809978-d34be21f-f1f6-46cb-b46c-ea5760b87661.png)

**Comment by Huuums** [comment]
Thanks for the pointer! Will definitely fix this soon.
