### ISSUE TITLE
Absolute path configuration doesn't seem to work correctly.

### ISSUE THREAD

**Issue by Huuums** [Huuums/vscode-folder-templates#94]
Having a little trouble making it work.

![Mar-03-2022 12-51-28](https://user-images.githubusercontent.com/678806/156559584-6daf1add-4db8-41cb-9c0b-a61bafa6e536.gif)

> .fttemplates/.ftsettings.json

```json
{
  "omitParentDirectory": true,
  "absolutePath": true,
  "overwriteExistingFiles": "prompt"
}
```

it keeps creating `Example/screens/ExampleScreen/index.tsx` - would like to avoid the root `Example/` and have it create the file in `screens`.

_Originally posted by @Norfeldt in https://github.com/Huuums/vscode-folder-templates/issues/82#issuecomment-1057965328_

**Comment by Norfeldt** [comment]
Thanks @Huuums you saved my day 👍

<img width="229" alt="Screenshot 2022-03-07 at 21 33 20" src="https://user-images.githubusercontent.com/678806/157113621-12bb2dc1-9aa0-4016-8e3e-a8b1edad4dc3.png">

**Comment by Norfeldt** [comment]
Just a little something to say thank you. 
Made these icons in case you wanna update the extension icon:

![icon-2](https://user-images.githubusercontent.com/678806/157119343-0e70d007-d99a-4d9b-9a8d-1108198b6b32.png)
![icon-3](https://user-images.githubusercontent.com/678806/157119346-33e9869a-2d22-4b24-a8a0-b625f9ecd005.png)
![icon-4](https://user-images.githubusercontent.com/678806/157119348-5fd8d6a7-7102-4a6c-be39-3a49fce6d89a.png)
![icon-5](https://user-images.githubusercontent.com/678806/157119349-4827cc13-5b50-4273-b6ca-4a58ab15c026.png)
![icon-1](https://user-images.githubusercontent.com/678806/157119352-da9a7a6a-5944-4dce-800c-e9dce297e21c.png)
![icon-6](https://user-images.githubusercontent.com/678806/157119353-314f5604-d0ee-4564-ae60-a71a627693d0.png)
![icon-7](https://user-images.githubusercontent.com/678806/157119364-6716050d-f6dc-4be1-9609-af4988b68b41.png)
![icon-8](https://user-images.githubusercontent.com/678806/157119366-8a738f6d-ee7f-43c0-afa2-39675717c9ad.png)
![icon](https://user-images.githubusercontent.com/678806/157119367-b23a4e7d-a22a-46d6-89a6-0ea0e4d6d13d.png)

**Comment by Norfeldt** [comment]
> @Norfeldt I went ahead and created its own issue for this problem. 
> 
> 
> 
> Can you please provide your template you're using for this so I can easily reproduce this? 
> 
> 
> 
> I will take a look then
> 
> 
> 
> Edit: Actually I think I might already see the problem. 
> 
> 
> 
> the `ftsettings.json` should go into the `screens` folder since that file is supposed to be a config on a _per template_ basis.
> 
> 
> 
> Could you please try that and then try again? 

You can close the issue now 🙂
