### ISSUE TITLE
Strange Warning: $ref 'definitions/string_nonempty' can not be resolved.

### ISSUE THREAD

**Issue by joaorr3** [Huuums/vscode-folder-templates#96]
#### I keep getting this warning at the top of .json files. This doesn't block my workflow but i thought in let you know because it can get a bit annoying to keep seeing a warning that can only be resolved by disabling the extension.

![image](https://user-images.githubusercontent.com/38807975/161050190-c839a417-8fa6-4f43-b47c-fdad482b54ee.png)

https://github.com/Huuums/vscode-folder-templates/blob/master/schemas/defs.json#L5

Thank you

**Comment by andrecastelo** [comment]
I'm also having this issue.

**Comment by Huuums** [comment]
Thanis. I will try to fix this very soon. Sorry for that.

**Comment by Huuums** [comment]
fixed in #97 and published as version 3.8.1. 

The warning should no longer be there after the update.

**Comment by joaorr3** [comment]
Yes, it's fixed. Thank you!
